### PR TITLE
fix(flexn/template): tv with bundle assets error

### LINKED ISSUE #44: [tvOS, AndroidTV] Template test scheme build can't be launched with "bundleAssets": true
ReNative Version: 0.36.0-canary.13
Project Version ($package.version): 0.15.0

How to repro:
1. Do `yarn e2e-template-tvos` or `yarn e2e-template-androidtv` -> error

This is how test scheme looks:
```
"test": {
                    "signingConfig": "Debug",
                    "bundleAssets": true
                },
```

Screenshot 2022-06-06 at 12 18 56

Screenshot 2022-06-06 at 12 16 31

Related to https://github.com/renative-org/renative/issues/876

### PR DESCRIPTION
**Pull request by locksten**
Fixes #44

### CODE REVIEW

**Comment by pauliusguzas** [comment]
@locksten supposedly does not fix the issue (can be seen from the actions)

**Comment by locksten** [comment]
@pauliusguzas it's due to the "Now Try Me!" button test failing:

Screen Shot 2022-09-16 at 12 16 29

I fixed the preceding test not properly returning to the home screen, but for some reason
`await FlexnRunner.expectToBeDisplayedById('template-carousels-screen-container');`
still fails, even though the carousels screen is displayed, and the same check in an earlier test succeeds.
Any idea what could be causing this @pauliusguzas ?

https://user-images.githubusercontent.com/9592076/190617838-4af9032a-3f2d-4030-888e-d79d7c23da10.mp4

**Comment by pauliusguzas** [comment]
Will investigate it, though atv I see is failing on all tests

**Comment by locksten** [comment]
@pauliusguzas  I ran `yarn e2e-template-androidtv` locally with just the `await FlexnRunner.pressButtonRight(1);` fix and it passed all tests:

https://user-images.githubusercontent.com/9592076/190659873-5bb5ab93-da0c-4e19-8a70-3a781c515980.mp4

**Comment by pauliusguzas** [comment]
@locksten Yeah the issue is with template, drawer does not close automatically and that causes wrong page opening on last test. I can confirm that your fix is valid, basically template is broken, tests themself do not need to be changed. It is expected to fail if the app is broken

**Review by pauliusguzas — APPROVED** [review]

**Pull request merged**
